import hashlib
m = hashlib.sha256()
m.update(b"abcde")
m.update(b"fghijk")
h = m.digest()
h_hex = m.hexdigest()
print("hash in byte: ", h)
print("hash in hex: ", h_hex)
ms = hashlib.sha256()
ms.update(b"abcdefghijk")
hs = ms.digest()
hs_hex = ms.hexdigest()
print("hash in byte: ", hs)
print("hash in hex: ", hs_hex)